apiVersion: v1
kind: Service
metadata:
  name: cnappforazuredev
spec:
  selector:
    app: cnappforazuredev
  ports:
  - protocol: TCP
    name: http-public
    port: 80
    targetPort: 31080
  type: LoadBalancer