version: '3.4'

services:
  cnacatalogservice:
    image: ${DOCKER_REGISTRY-}cnacatalogservice
    build:
      context: .
      dockerfile: CnaCatalogService/Dockerfile
    environment:
      AccountKey: "codz0v7RAb2KNnpvBMfsKVgl+wockK00SpDw50eCcbnAwYwT+/WdjSp2udeZHmMAba2bl2tQQC7ZxvV15am7gQ=="
      AccountName: "cnas02ncstorage"
      CatalogName: "catalog"
      ContainerName: "images"
      MaxItems: "12"

  webappui:
    image: ${DOCKER_REGISTRY-}webappui
    build:
      context: .
      dockerfile: WebAppUI/Dockerfile
    ports:
      - 31080:31080
    environment:
      MOTD: "MOTD via DockerCompose"
      CatalogItemsServiceUrl: "http://cnacatalogservice:32080/api/catalogItems"

